version: '2'

services:
    nginx:
        image: nginx:1.11.6-alpine
        container_name: nginx
        restart: always
        ports:
            - 8000:8000
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - backend
    mariadb:
        restart: always
        image: mariadb
        container_name: mariadb
        volumes:
            - ./docker/mariadb:/data
        command: --init-file /data/init_db.sql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
        expose:
            - 3306
    backend:
        container_name: backend
        restart: always
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        volumes:
            - .:/django
        links:
            - mariadb
        entrypoint:
            - /django-entrypoint.sh
        expose:
            - 8000
    frontend:
        container_name: frontend
        restart: always
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        volumes:
            - .:/django

        links:
            - backend
        entrypoint:
            - /web-entrypoint.sh
    redis:
        container_name: redis
        image: "redis:alpine"
        ports:
          - "6373:6373"
        container_name: redis
